# Generated by Django 2.2.5 on 2019-10-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
