# Generated by Django 2.2.5 on 2019-10-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20191001_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
