# Generated by Django 2.2.5 on 2019-10-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectpost_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
    ]
